AWSTemplateFormatVersion: '2010-09-09'
Description: Static web hosting Certificate creation
Parameters:
  DomainName:
    Description: Name of the domain you want to obtain the certificate
    Type: String
  HostedZoneId:
    Description: Id of the hosted zone 
    Type: String
Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

Outputs:
  CertificateArn: 
    Description: Issued certificate
    Value: !Ref Certificate